In [3]:
import pandas as pd
production=pd.Series([30,60,45,25],index=['wheat','rice','maize','ragi'])
print(production)

wheat    30
rice     60
maize    45
ragi     25
dtype: int64

In [4]:
print(production['rice'])

60

In [6]:
print(production.loc['rice'])

60

In [7]:
print(production[0])

30

C:\Users\keert\AppData\Local\Temp\ipykernel_21020\1985089337.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(production[0])

In [20]:
print(production.iloc[0])

30

In [11]:
print(production.sum())

160

In [12]:
print(production.mean())

40.0

In [15]:
print(production.idxmax())

rice

In [14]:
print(production.max())

60

In [16]:
print(production.idxmin())

ragi

In [21]:
#crops with production greater than 40 tonnes
high_production=production[production>40]
print(high_production)
print()
print(production>40)

rice     60
maize    45
dtype: int64

wheat    False
rice      True
maize     True
ragi     False
dtype: bool

In [25]:
#dataframe -two dimensions
df=pd.DataFrame({
    'name':['Akhil','Bobby','Charan'],
    'age':[25,30,35],
    'city':['NY','LA','Chicago']
},index=['a','b','c'])
print(df)
print()
print(df.loc['b'])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

name    Bobby
age        30
city       LA
Name: b, dtype: object

In [26]:
print(df)
print()
print(df.loc[['a','c'],['name','city']])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

     name     city
a   Akhil       NY
c  Charan  Chicago

In [27]:
print(df.loc['a':'c']) #end of the slice is included

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LA
c  Charan   35  Chicago

In [29]:
print(df.iloc[0:2]) #end of the slice is excluded

    name  age city
a  Akhil   25   NY
b  Bobby   30   LA

In [3]:
import pandas as pd
df=pd.DataFrame({
    'name':['Akhil','Bobby','Charan'],
    'age':[25,30,35],
    'city':['NY','LA','Chicago']
},index=['a','b','c'])
print(df.loc[df['age']>28,['name','age']]) #conditional statement

     name  age
b   Bobby   30
c  Charan   35

In [11]:
print(df.iloc[[0,2]])

     name  age     city
a   Akhil   25       NY
c  Charan   35  Chicago

In [6]:
print(df.iloc[0:2])

    name  age city
a  Akhil   25   NY
b  Bobby   30   LA

In [7]:
print(df.iloc[[0,2],[1,2]])

   age     city
a   25       NY
c   35  Chicago

In [12]:
df['name']

a     Akhil
b     Bobby
c    Charan
Name: name, dtype: object

In [13]:
df['age']

a    25
b    30
c    35
Name: age, dtype: int64

In [14]:
df['city']

a         NY
b         LA
c    Chicago
Name: city, dtype: object

In [19]:
import pandas as pd
data={
    'Farm':['Farm A','Farm B','Farm C','Farm D'],
    'Crop':['Wheat','Rice','Wheat','Maize'],
    'Area_hectares':[10,15,8,12],
    'Production_tons':[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)
df.head()

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [20]:
df.head(2)

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60

In [21]:
df.tail(2)

     Farm   Crop  Area_hectares  Production_tons
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Farm             4 non-null      object
 1   Crop             4 non-null      object
 2   Area_hectares    4 non-null      int64
 3   Production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [24]:
df.describe()

       Area_hectares  Production_tons
count       4.000000         4.000000
mean       11.250000        37.500000
std         2.986079        15.779734
min         8.000000        24.000000
25%         9.500000        28.500000
50%        11.000000        33.000000
75%        12.750000        42.000000
max        15.000000        60.000000

In [42]:
df['yield_ton_per_hectare']=df['Production_tons']/df['Area_hectares']
df

,Farm,Crop,Area_hectares,Production_tons,yield_ton_per_hectare,Yield_ton_per_hectare,yiled_ton_per_hectare
0,Farm A,Wheat,10,30,3.0,3.0,3.0
1,Farm B,Rice,15,60,4.0,4.0,4.0
2,Farm C,Wheat,8,24,3.0,3.0,3.0
3,Farm D,Maize,12,36,3.0,3.0,3.0

In [41]:
df.iloc[[1,3],[0,1,2]]

     Farm   Crop  Area_hectares
1  Farm B   Rice             15
3  Farm D  Maize             12

In [40]:
df.iloc[[1,3]]

,Farm,Crop,Area_hectares,Production_tons,yield_ton_per_hectare,Yield_ton_per_hectare,yiled_ton_per_hectare
1,Farm B,Rice,15,60,4.0,4.0,4.0
3,Farm D,Maize,12,36,3.0,3.0,3.0

In [46]:
#filter data
#farms growing wheat
print(df['Crop']=='Wheat')
print()
wheat_farms=df[df['Crop']=='Wheat']
print(wheat_farms)

0     True
1    False
2     True
3    False
Name: Crop, dtype: bool

     Farm   Crop  Area_hectares  Production_tons  yield_ton_per_hectare  \
0  Farm A  Wheat             10               30                    3.0
2  Farm C  Wheat              8               24                    3.0

   Yield_ton_per_hectare  yiled_ton_per_hectare
0                    3.0                    3.0
2                    3.0                    3.0

In [47]:
high_yield=df[df['Yield_ton_per_hectare']>3]
high_yield

,Farm,Crop,Area_hectares,Production_tons,yield_ton_per_hectare,Yield_ton_per_hectare,yiled_ton_per_hectare
1,Farm B,Rice,15,60,4.0,4.0,4.0

In [48]:
sorted_df=df.sort_values(by='Production_tons',ascending=False) #sort farms by highest production
sorted_df

,Farm,Crop,Area_hectares,Production_tons,yield_ton_per_hectare,Yield_ton_per_hectare,yiled_ton_per_hectare
1,Farm B,Rice,15,60,4.0,4.0,4.0
3,Farm D,Maize,12,36,3.0,3.0,3.0
0,Farm A,Wheat,10,30,3.0,3.0,3.0
2,Farm C,Wheat,8,24,3.0,3.0,3.0

In [49]:
#GroupBy operation-avg yield per crop
avg_yield=df.groupby('Crop')['Yield_ton_per_hectare'].sum()
avg_yield

Crop
Maize    3.0
Rice     4.0
Wheat    6.0
Name: Yield_ton_per_hectare, dtype: float64